### PR TITLE
Fixed MPI issue

### PR DESCRIPTION
**Pull request by setsuna0402**
Avoid lack of memory;
If LocalNumberOfStars becomes zero, reinitialise sendbuffer and reset sendBufferSize.(MPI issue)

### CODE REVIEW

**Comment by jwise77** [comment]
Thanks for submitting this PR! I'll review it and find two more reviewers, as we require three approvals to merge.

**Comment by setsuna0402** [comment]
I guess we fixed the incompatibility with yt-4.0. Maybe we should go back to this pull request?

**Comment by gregbryan** [comment]
Yes, apologies for the delay. Can you pull in that fix which should hopefully fix the tests.

**Review by fearmayo — APPROVED** [review]

**Comment by jwise77** [comment]
Hi @setsuna0402 I want to run the tests on this PR before merging after the latest changes to the test suite. I've merged in the changes on my local copy of your fork, but I'm getting permission denied to push. Can you check if "Allow edits by maintainers" is selected on the bottom of the right sidebar? Thanks!

**Comment by setsuna0402** [comment]
@jwise77  Sorry, I didn't received your msg.  How to change "Allow edits by maintainers"?

**Comment by jwise77** [comment]
> @jwise77 Sorry, I didn't received your msg. How to change "Allow edits by maintainers"?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by setsuna0402** [comment]
@jwise77  I checked the "Allow edits by maintainers" button, and I think I have selected it since the first day. BTW, it is selected now.

**Comment by jwise77** [comment]
@setsuna0402 I fixed the testing in #190, and I merged in these changes to run the test suite on this PR. But I couldn't push the tags to your PR. Could you issue the command `git fetch https://github.com/jwise77/enzo-dev --tags` and then `git push` to bring in the new gold-standard-v15 tag for testing?

**Comment by jwise77** [comment]
> @setsuna0402 I fixed the testing in #190, and I merged in these changes to run the test suite on this PR. But I couldn't push the tags to your PR. Could you issue the command `git fetch https://github.com/jwise77/enzo-dev --tags` and then `git push --tags` to bring in the new gold-standard-v15 tag for testing?

Not needed anymore after #190 was merged.

**Pull request merged**
