### PR TITLE
Resurrect GalaxySim Functionality

### PR DESCRIPTION
**Pull request by clairekope**
Early in the development of merge #191 I had deleted some code I didn't need, forgotten about it, and now I've put it back for full backwards compatibility (as it were) of Enzo and the GalaxySimulation problem type. To reconcile the old code with my changes I have added some new parameters.

Primarily, these parameters decide: which static dark matter potential to use (both during disk initialization and during sim runtime), and whether to use an isothermal initial disk or the thermally pressure balanced disk from Tonnesen & Bryan 09.

Bonus content: 
* there's a machine file for SDSC Expanse
* CircleCI will save `out.compile` as an artifact of `test-compile-options`, so that if linking fails, it can be debugged.

### CODE REVIEW

**Comment by clairekope** [comment]
test-compile-options is failing while linking but doesn't fail locally.
The test-suite is failing to compile `RadiativeTransferWriteParameters.C` which was not modified in this PR. Error is about `size_t` being undefined, with suggested alternative `__size_t`. This error doesn't occur when building locally.

**Review by bwoshea — APPROVED** [review]
Looks good to me!

**Comment by bwoshea** [comment]
Looks good.  @clairekope there's a merge conflict - if you can fix that we can go ahead and merge!

**Comment by clairekope** [comment]
> Looks good. @clairekope there's a merge conflict - if you can fix that we can go ahead and merge!

Done!

**Comment by clairekope** [comment]
Doc build is fixed by #207 and works offline

**Comment by bwoshea** [comment]
Since the docs-build issue is fixed in another PR, I am going to go ahead and merge this PR.

**Pull request merged**
