### PR TITLE
Added StarFormationOncePerRootGridTimeStep to Normal Star

### PR DESCRIPTION
**Pull request by clairekope**
Extended existing `StarFormationOncePerRootGridTimeStep` functionality to Normal Star (star_maker2.F). Also adjusted what grids `StarFormationOncePerRootGridTimeStep` triggers on. Previously, it only allowed star formation on grids that were at the maximum refinement level. Since each star maker routine checks that a cell is the most refined representation for its volume, this restriction is unnecessary and prevents star formation in cells where it would otherwise occur.

### CODE REVIEW

**Review by bwoshea — APPROVED** [review]
This looks good to me!

**Review by brittonsmith — COMMENTED** [review]
The code looks good to me. @clairekope, could you also update the documentation on this parameter? It's in `doc/manual/source/parameters/index.rst`.

**Review by brittonsmith — APPROVED** [review]
Thanks for updating the docs! Looks great to me.

**Comment by bwoshea** [comment]
Thanks, @brittonsmith !  I'm going to merge the PR now.

**Pull request merged**
