### PR TITLE
Correcting MBHAccretion parameter to SmartStarAccretion in SmartStar module

### PR DESCRIPTION
**Pull request by simonetgordon**
Discussed change with creator of SmartStar module, John Regan. MBHAccretion parameter was used in code instead of the parameter which appeared in the docs, SmartStarAccretion.

### CODE REVIEW

**Comment by brittonsmith** [comment]
Thanks for doing this, @simonetgordon! There is one test that uses the smart stars with this parameter. It is `run/Hydro/Hydro-3D/CollapseTestSmartStars/CollapseTestSmartStars.enzo`. Can you change it in there, too?

**Review by jwise77 — APPROVED** [review]

**Review by brittonsmith — APPROVED** [review]

**Review by fearmayo — APPROVED** [review]

**Comment by fearmayo** [comment]
Thanks @simonetgordon !

**Comment by gregbryan** [comment]
Thanks @simonetgordon!  This has three approvals and so I'm merging...

**Comment by jwise77** [comment]
I just resolved a conflict from #165

**Comment by gregbryan** [comment]
Thanks @jwise77 !  Actually, I'm holding off merging because I see that there is only one test run on this, rather than the expected 4.  Does anyone know why?

**Pull request merged**
