### PR TITLE
Star Particle Communication Bugfixes

### PR DESCRIPTION
**Pull request by aemerick**
This fixes / improves star particle communication to address memory fragmentation and performance issues when running with many (> 10k) star particle objects.

These changes are all circa 2016, but fell through the cracks in getting pulled into the main repository. Caught this when merging my fork with the active particle changes. Some of these changes parallel what is done with active particles. 

All credit goes to John Wise, stemming from the following commits: [May 2016 (1 of 2)](https://bitbucket.org/jwise77/enzo-dev/commits/ba5202af3d2c6102bd82ca644fed3c373e6552e8), [May 2016 (2 of 2)](https://bitbucket.org/jwise77/enzo-dev/commits/703f1091d58a4e12cc6720bc08ef12581e56792f), [June, 2016](https://bitbucket.org/jwise77/enzo-dev/commits/2981eb07b9effb06e490a38047fefa5bfb8237a2)

### CODE REVIEW

**Comment by aemerick** [comment]
Sorry all, just noticed that this includes two unrelated commits. 

One fixes what I thought was a bug but is on a commented out bit of code so is mostly irrelevant.

The other adds the kphHM and kdissH2II fields to the radiation / density field macros to be consistent with what is done with the other radiation fields. Not quite sure if this needs to be done or not.

**Comment by bwoshea** [comment]
@aemerick  could you please update your pull request using the tip of the enzo-dev repository?  We updated the gold standard for tests.

**Comment by brittonsmith** [comment]
This PR has been hanging around for a while now. Is it ready to be merged?

**Comment by bwoshea** [comment]
I think so!

**Pull request merged**
