### PR TITLE
Hybrid MPI/OpenMP functional prototype

### PR DESCRIPTION
**Pull request by cjllorente827**
I've introduced OpenMP threading to some of Enzo's routines and achieved a reasonable performance boost for small numbers of threads. I've also added some documentation explaining the philosophy of how the sections have been added, how to compile and run this version of Enzo, and results from some small-scale performance tests.

### CODE REVIEW

**Comment by bwoshea** [comment]
Just a quick followup: @cjllorente827 is going to fix the merge conflicts first.  @cjllorente827 , once you update your code to be compatible with the tip of enzo-dev/master, a third set of tests will also run to do compile testing.  This may cause some extra issues with the testing that could cause it to crash!

**Comment by bwoshea** [comment]
Er, also, sorry about closing and then opening the PR just there.  The "comment" and "close and comment" buttons are a bit too close together.  :-)

**Comment by pgrete** [comment]
I'm happy to review the changes once the merge conflicts are resolved as Brian suggested.

**Comment by pgrete** [comment]
Speaking of tests: Is there any automated regression test that verify that the OpenMP results are identical (to a sufficient degree) to the ones without, @cjllorente827 ?

**Comment by bwoshea** [comment]
@cjllorente827 followup up on this - how are things going with resolving merge conflicts?

**Comment by cjllorente827** [comment]
@pgrete  There's nothing automated in place to test solution correctness. That testing was done manually by another undergraduate at Georgia Tech, Doug Stewart. 
@bwoshea I'll look into fixing the merge conflicts some time next week my first midterm is over.

**Comment by pgrete** [comment]
Given the fundamental change in parallelism I then suggest to add at least a few basic tests (especially with respect to future changes) to ensure that the results are (and remain) correct.

**Comment by bwoshea** [comment]
> Given the fundamental change in parallelism I then suggest to add at least a few basic tests (especially with respect to future changes) to ensure that the results are (and remain) correct.

This makes sense.  @brittonsmith , does CircleCI's testing support thread-based parallelism for testing purposes?

**Comment by brittonsmith** [comment]
@bwoshea, yes, I think you can have a maximum of 36 total threads on a circleci testing node. Set `OMP_NUM_THREADS` as you would normally and it'll work.

**Comment by bwoshea** [comment]
@cjllorente827  could you please update your pull request using the tip of the enzo-dev repository?  We updated the gold standard for tests.

**Comment by jwise77** [comment]
Ping @cjllorente827 . We updated the gold standard again after a bug was introduced and subsequently fixed. Can you merge in the `enzo-project:master` branch so the tests can run again?

**Comment by bwoshea** [comment]
Declined as per conversation with @cjllorente827 - he will issue another PR shortly.

**Pull request closed without merging**
